### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by kashifeqbal** [pevers/images-scraper#33]
run this command `npm install images-scraper --save`
got this error in console
```
> electron@1.8.4 postinstall /Users/kashifeqbal/Development/accio.brands.version.1/node_modules/electron
> node install.js

Downloading electron-v1.8.4-darwin-x64.zip
[============================================>] 100.0% of 48.34 MB (917.1 kB/s)
/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/electron/install.js:47
  throw err
  ^

Error: Generated checksum for "electron-v1.8.4-darwin-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.Error (native)
    at ChecksumMismatchError.ErrorWithFilename (/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/sumchecker/build.js:41:124)
    at new ChecksumMismatchError (/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/sumchecker/build.js:56:133)
    at Hash.<anonymous> (/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/sumchecker/build.js:203:22)
    at emitNone (events.js:86:13)
    at Hash.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Hash.Readable.push (_stream_readable.js:134:10)
⸨                ░░⸩ ⠏ postinstall: info lifecycle electron@1.8.4~postinstall: Failed to exec postinstall script




accio_brands@1.0.0 /Users/kashifeqbal/Development/accio.brands.version.1
└── UNMET PEER DEPENDENCY chai@4.1.2

npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/expand-brackets/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/express/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/loopback-connector/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/loopback-phase/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/loopback-swagger/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/send/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/snapdragon/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/stream-parser/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/strong-remoting/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kashifeqbal/Development/accio.brands.version.1/node_modules/x-ray-crawler/package.json'
npm WARN chai-as-promised@5.3.0 requires a peer of chai@>= 2.1.2 < 4 but none was installed.
npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "images-scraper" "--save"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.8.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.4 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kashifeqbal/Development/accio.brands.version.1/npm-debug.log
npm ERR! code 1
```

**Comment by tecfu** [comment]
Try: 

```
$ sudo npm i -S --unsafe-perm=true --allow-root
```

**Comment by pevers** [comment]
See @tecfu
