### ISSUE TITLE
Nightmare memory leak

### ISSUE THREAD

**Issue by davguij** [pevers/images-scraper#6]
Google scraping fails completely. This is part of the console log:
```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:252:17)
    at EventEmitter.once (events.js:278:8)
    at EventEmitter.<anonymous> (D:\my\images-scraper\node_modules\nightmare\lib\runner.js:249:14)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at process.<anonymous> (D:\my\images-scraper\node_modules\nightmare\lib\ipc.js:28:10)
    at emitTwo (events.js:105:20)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by pevers** [comment]
Thanks! Ill be working on it tonight!

**Comment by davguij** [comment]
Great to hear.
To give you some more context, Nightmare fails on Win7.
I've spun up a VM with Ubuntu and Nightmare works fine, but I get a `Cannot read property 'match' of undefined` error :(

**Comment by pevers** [comment]
Seems to be fixed now, can you test it again on Windows? I also updated Nightmare to the latest version.

**Comment by davguij** [comment]
Works now. Sort of.
I've tested on Windows 7, freshly installed Node.js 4.4.3.
I ran the example code. I actually got the 10 first results from Google, but right after that console spits an error:
```
D:\my\scraper>[10812:0426/104926:FATAL:memory.cc(19)] Out of memory. size=4194304
Backtrace:
        (No symbol) [0x00000001400273F1]
        (No symbol) [0x000000014002083C]
        icu_54::Transliterator::setID [0x000000014295C4AB+705019]
        icu_54::MessagePattern::partSubstringMatches [0x0000000142D7DD45+4280965]
        icu_54::MessagePattern::partSubstringMatches [0x0000000142D7D900+4279872]
        IsSandboxedProcess [0x000000014198FEA5+237589]
        IsSandboxedProcess [0x00000001419C8600+468848]
        IsSandboxedProcess [0x00000001419A1970+309984]
        IsSandboxedProcess [0x00000001419C9FAD+475421]
        IsSandboxedProcess [0x0000000141A681DB+1123147]
        IsSandboxedProcess [0x0000000141A68A3A+1125290]
        IsSandboxedProcess [0x0000000141A682C2+1123378]
        IsSandboxedProcess [0x00000001419CF8A4+498196]
        icu_54::MessagePattern::partSubstringMatches [0x0000000142C18DAE+2818798]
        icu_54::TimeZone::setID [0x0000000140983C79+7467993]
        GetHandleVerifier [0x00000001400968CB+254251]
        GetHandleVerifier [0x0000000140096BE6+255046]
        (No symbol) [0x0000000140050B27]
        BaseThreadInitThunk [0x00000000776A59ED+13]
        RtlUserThreadStart [0x00000000779FB371+33]
```
However, if I use
```
    detail: false,
    nightmare: {
        show: false
    }
```
the error disappears.
Totally usable now, though, so good job and thanks!
